version: '3.5'

services:
  db:
    container_name: ${SERVICE_NAME}-db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_PORT: 3306
    volumes:
      - ./data/db:/usr/share/mysql/data
      - ./db/conf/:/etc/mysql/conf.d
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - ${SERVICE_NAME}-network
    ports:
      - 3307:3306
  php:
    build:
      context: ${PACKAGE_FOLDER}
      dockerfile: ./docker/php/Dockerfile
      target: base
    container_name: ${SERVICE_NAME}-php
    working_dir: /${PUBLIC_ROOT}
    volumes:
      - ./${PACKAGE_FOLDER}/:/${PUBLIC_ROOT}/:rw,cached
    environment:
      - WITH_XDEBUG=true
    networks:
      - ${SERVICE_NAME}-network

  nginx:
    image: nginx:latest
    container_name: ${SERVICE_NAME}-nginx
    depends_on:
      - php
    ports:
      - "8202:80"
    volumes:
      - ./${PACKAGE_FOLDER}:/${PUBLIC_ROOT}/:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:rw,delegated
    links:
      - php
    environment:
      - WITH_XDEBUG=true
      - COMMIT_HASH='your uncle'
    networks:
      - ${SERVICE_NAME}-network
#  newman:
#    container_name: ${SERVICE_NAME}-newman
#    image: postman/newman:ubuntu
#    volumes:
#     - ../tests/postman:/postman:delegated

volumes:
  appdata:
    driver: local

networks:
  demo-api-microservice-network:
#    name: ${SERVICE_NAME}-network
